data:
  image: busybox:latest
  volumes:
    - ./:/app
  entrypoint: tail -f /dev/null

app:
  build: docker/php
  working_dir: /app
  volumes_from:
    - data
  expose:
    - 9000
  links:
    - db
    - mailcatcher
  environment:
    XDEBUG_CONFIG: "idekey=PHPSTORM remote_enable=On remote_connect_back=On"

nginx:
  image: nginx:latest
  ports:
    - "8888:80"
  volumes:
    - ./:/app
    - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
  links:
    - app

mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "1080:1080"

db:
  image: postgres:9.6.0
  volumes:
    - /var/lib/postgresql/data
  ports:
     - "5454:5432"
  environment:
    POSTGRES_USER: plugin
    POSTGRES_PASSWORD: plugin
    POSTGRES_DB: plugin